-- Table schema for CampusSmartLifeDB.
-- npm run db:init drops and recreates the target database before applying this file.

IF OBJECT_ID(N'dbo.Users', N'U') IS NULL
CREATE TABLE dbo.Users (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  Account NVARCHAR(64) NOT NULL UNIQUE,
  Phone NVARCHAR(32) NULL,
  OpenId NVARCHAR(128) NULL,
  Role NVARCHAR(32) NOT NULL DEFAULT N'student',
  PasswordHash NVARCHAR(255) NOT NULL,
  Nickname NVARCHAR(80) NOT NULL,
  Avatar NVARCHAR(255) NULL,
  StudentNo NVARCHAR(64) NULL,
  Contact NVARCHAR(128) NULL,
  SchoolVerified BIT NOT NULL DEFAULT 0,
  CreditScore INT NOT NULL DEFAULT 90,
  CreditLevel NVARCHAR(16) NOT NULL DEFAULT N'A',
  Muted BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Invitations', N'U') IS NULL
CREATE TABLE dbo.Invitations (
  Code NVARCHAR(64) NOT NULL PRIMARY KEY,
  CreatedBy NVARCHAR(64) NOT NULL,
  UsedBy NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  LimitCount INT NOT NULL DEFAULT 30,
  ExpiresAt DATETIME2 NOT NULL
);
GO

IF OBJECT_ID(N'dbo.Tasks', N'U') IS NULL
CREATE TABLE dbo.Tasks (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  Title NVARCHAR(160) NOT NULL,
  Type NVARCHAR(32) NOT NULL,
  Reward DECIMAL(10, 2) NOT NULL,
  Deadline NVARCHAR(80) NOT NULL,
  Distance NVARCHAR(80) NULL,
  Location NVARCHAR(160) NULL,
  Detail NVARCHAR(MAX) NULL,
  Deliverable NVARCHAR(160) NULL,
  PublisherId NVARCHAR(64) NOT NULL,
  AssigneeId NVARCHAR(64) NULL,
  Applicants NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  Status NVARCHAR(32) NOT NULL,
  EscrowPaid BIT NOT NULL DEFAULT 0,
  Views INT NOT NULL DEFAULT 0,
  DeliveryJson NVARCHAR(MAX) NULL,
  SettlementJson NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Posts', N'U') IS NULL
CREATE TABLE dbo.Posts (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  AuthorId NVARCHAR(64) NOT NULL,
  Title NVARCHAR(160) NOT NULL,
  Content NVARCHAR(MAX) NOT NULL,
  Type NVARCHAR(32) NOT NULL,
  Topics NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  Images NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  Likes NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  Favorites NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  Shares INT NOT NULL DEFAULT 0,
  Views INT NOT NULL DEFAULT 0,
  Status NVARCHAR(32) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Comments', N'U') IS NULL
CREATE TABLE dbo.Comments (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  PostId NVARCHAR(64) NOT NULL,
  AuthorId NVARCHAR(64) NOT NULL,
  Content NVARCHAR(MAX) NOT NULL,
  Likes NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  ParentId NVARCHAR(64) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Goods', N'U') IS NULL
CREATE TABLE dbo.Goods (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  SellerId NVARCHAR(64) NOT NULL,
  Name NVARCHAR(160) NOT NULL,
  Category NVARCHAR(32) NOT NULL,
  Price DECIMAL(10, 2) NOT NULL,
  ConditionText NVARCHAR(32) NOT NULL,
  TradeMode NVARCHAR(32) NOT NULL,
  Location NVARCHAR(160) NULL,
  Description NVARCHAR(MAX) NULL,
  Images NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  Status NVARCHAR(32) NOT NULL,
  AuditStatus NVARCHAR(32) NOT NULL,
  Views INT NOT NULL DEFAULT 0,
  Consults INT NOT NULL DEFAULT 0,
  Favorites NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Orders', N'U') IS NULL
CREATE TABLE dbo.Orders (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  GoodsId NVARCHAR(64) NOT NULL,
  BuyerId NVARCHAR(64) NOT NULL,
  SellerId NVARCHAR(64) NOT NULL,
  Amount DECIMAL(10, 2) NOT NULL,
  Status NVARCHAR(32) NOT NULL,
  EscrowPaid BIT NOT NULL DEFAULT 0,
  Address NVARCHAR(160) NULL,
  PaymentJson NVARCHAR(MAX) NULL,
  ReviewsJson NVARCHAR(MAX) NULL,
  DisputeJson NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Conversations', N'U') IS NULL
CREATE TABLE dbo.Conversations (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  ParticipantIds NVARCHAR(MAX) NOT NULL,
  MutedBy NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  Source NVARCHAR(64) NULL,
  RelatedCard NVARCHAR(MAX) NULL,
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Messages', N'U') IS NULL
CREATE TABLE dbo.Messages (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  ConversationId NVARCHAR(64) NOT NULL,
  FromUserId NVARCHAR(64) NOT NULL,
  Type NVARCHAR(32) NOT NULL,
  Content NVARCHAR(MAX) NULL,
  CardJson NVARCHAR(MAX) NULL,
  ReadBy NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Notifications', N'U') IS NULL
CREATE TABLE dbo.Notifications (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  UserId NVARCHAR(64) NOT NULL,
  Type NVARCHAR(64) NOT NULL,
  Title NVARCHAR(160) NOT NULL,
  Content NVARCHAR(MAX) NULL,
  IsRead BIT NOT NULL DEFAULT 0,
  RelatedType NVARCHAR(32) NULL,
  RelatedId NVARCHAR(64) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Reports', N'U') IS NULL
CREATE TABLE dbo.Reports (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  TargetType NVARCHAR(32) NOT NULL,
  TargetId NVARCHAR(64) NOT NULL,
  ReporterId NVARCHAR(64) NOT NULL,
  Reason NVARCHAR(MAX) NOT NULL,
  EvidenceJson NVARCHAR(MAX) NULL,
  Status NVARCHAR(32) NOT NULL,
  Result NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.KnowledgeBase', N'U') IS NULL
CREATE TABLE dbo.KnowledgeBase (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  Category NVARCHAR(64) NOT NULL,
  Title NVARCHAR(160) NOT NULL,
  Content NVARCHAR(MAX) NOT NULL,
  Source NVARCHAR(160) NULL,
  Version INT NOT NULL DEFAULT 1,
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.Prompts', N'U') IS NULL
CREATE TABLE dbo.Prompts (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  Scene NVARCHAR(64) NOT NULL,
  Content NVARCHAR(MAX) NOT NULL,
  Version INT NOT NULL DEFAULT 1,
  Active BIT NOT NULL DEFAULT 1,
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID(N'dbo.AgentSessions', N'U') IS NULL
CREATE TABLE dbo.AgentSessions (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  UserId NVARCHAR(64) NOT NULL,
  Title NVARCHAR(160) NOT NULL,
  MessagesJson NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NULL
);
GO

IF OBJECT_ID(N'dbo.Audits', N'U') IS NULL
CREATE TABLE dbo.Audits (
  Id NVARCHAR(64) NOT NULL PRIMARY KEY,
  Type NVARCHAR(64) NOT NULL,
  Title NVARCHAR(160) NOT NULL,
  ActorId NVARCHAR(64) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
